---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ansible-runner.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ansible-runner.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave.rbac | quote }}
data:
  ansible.cfg: |
    [defaults]
    host_key_checking = False
    stdout_callback = default
    retry_files_enabled = False
    interpreter_python = auto_silent

  requirements.txt: |
    {{- range .Values.ansible.requirements }}
    {{ . }}
    {{- end }}

  collections.txt: |
    {{- range .Values.ansible.collections }}
    {{ . }}
    {{- end }}

  inventory.yaml: |
    all:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ "{{" }} ansible_playbook_python {{ "}}" }}"
